version: "3.9"
services:
  memcached:
    image: memcached
    ports:
      - "11211:11211"
  sauroneye:
    build: ./sauroneye
    working_dir: /app
    depends_on:
      - memcached
    environment:
      - MEMCHACHED_URL=memcached:11211
    volumes:
      - ./sauroneye/:/app/
  back:
    build: ./back
    ports:
      - 1323:1323
    environment:
      - MEMCHACHED_URL=memcached:11211
    volumes:
      - ./back/:/app/
    depends_on:
      - memcached
      - sauroneye
